/*
 iven two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

/**
思路：
[a]
[aa]
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    var hash = {};
    
    for (var i = 0; i < s.length; i++) {
        if (hash[s[i]] === undefined) hash[s[i]] = 1;
        else hash[s[i]] += 1;
    }
    
    for (var j = 0; j < t.length; j++) {
        if (hash[t[j]] === undefined || hash[t[j]] === 0) return t[j];
        else hash[t[j]] -= 1;
    }
};